# -*- coding: utf-8 -*-
"""Amazon User Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ho5Y_HLbO34J__XIjodFdCwiOTDv561X

Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Importing Dataset"""

dataset = pd.read_csv('/content/Amazon.csv')
X = dataset.iloc[:, [2,4]].values
y = dataset.iloc[:, -1].values

print(X)

X_clean = X[~np.isnan(X).any(axis=1)]

print(X_clean)

print(X)

from sklearn.impute import SimpleImputer

# Create an imputer to replace missing values with the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit the imputer to your data and transform it
X = imputer.fit_transform(X)

"""finding Optimal Number of Clusters using Elbow Method"""

from sklearn.cluster import KMeans
wcss = []
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=21)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)
plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

"""K Means model Training on Train Dataset"""

kmeans=KMeans(n_clusters=4,init='k-means++',random_state=42)
y_kmeans=kmeans.fit_predict(X)

print(y_kmeans)

"""Visualizing Clusters"""

plt.scatter(X[y_kmeans == 0, 0], X[y_kmeans == 0, 1], s = 100, c = 'magenta', label = 'Cluster 1')
plt.scatter(X[y_kmeans == 1, 0], X[y_kmeans == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(X[y_kmeans == 2, 0], X[y_kmeans == 2, 1], s = 100, c = 'red', label = 'Cluster 3')
plt.scatter(X[y_kmeans == 3, 0], X[y_kmeans == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], s = 300, c = 'black', label = 'Centroids')
plt.title('Clusters of Amazon Users')
plt.xlabel('Annual Income in INR')
plt.ylabel('Purchasing Rating')
plt.legend()
plt.show()

